In [1]:
import pandas as pd
import polars as pl

In [2]:
df_pandas = pd.read_parquet('primeirobimestre.parquet')

In [3]:
df_polars = pl.read_parquet('primeirobimestre.parquet')

In [4]:
display(df_pandas.head())
print('*********************************')
display(df_polars.head())

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
0,202401,202303,AC,139,RIO BRANCO,***.511.972-**,1.629112e+10,JANAINA FERREIRA DA SILVA,"800,00"
1,202401,202303,BA,3329,ANGUERA,***.909.745-**,2.047443e+10,TACIANE MARQUES DA SILVA,"750,00"
2,202401,202303,BA,3731,MONTE SANTO,***.872.338-**,2.019538e+10,MAILSON DOS SANTOS SILVA,"650,00"
3,202401,202303,BA,3761,NOVA VICOSA,***.665.905-**,1.272359e+10,IRENI RICARDO GERALDO,"650,00"
4,202401,202303,BA,3849,SALVADOR,***.932.435-**,2.002458e+10,ELIENE GOMES DOS SANTOS,"850,00"

*********************************

shape: (5, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ str       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202401     ┆ 202303     ┆ AC  ┆ 139        ┆ … ┆ ***.511.97 ┆ 1629111520 ┆ JANAINA   ┆ 800,00    │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 5          ┆ FERREIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3329       ┆ … ┆ ***.909.74 ┆ 2047442988 ┆ TACIANE   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 6          ┆ MARQUES   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3731       ┆ … ┆ ***.872.33 ┆ 2019537629 ┆ MAILSON   ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 8          ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3761       ┆ … ┆ ***.665.90 ┆ 1272358908 ┆ IRENI     ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 2          ┆ RICARDO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GERALDO   ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3849       ┆ … ┆ ***.932.43 ┆ 2002458400 ┆ ELIENE    ┆ 850,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 7          ┆ GOMES DOS ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [5]:
#Seleção de Colunas:
display(df_pandas["CÓDIGO MUNICÍPIO SIAFI"])

print('*********************************')

display(df_polars.select("CÓDIGO MUNICÍPIO SIAFI"))

0            139
1           3329
2           3731
3           3761
4           3849
            ...
41764968    9643
41764969    9643
41764970    9643
41764971    9643
41764972    9643
Name: CÓDIGO MUNICÍPIO SIAFI, Length: 41764973, dtype: int64

*********************************

shape: (41_764_973, 1)
┌────────────────────────┐
│ CÓDIGO MUNICÍPIO SIAFI │
│ ---                    │
│ i64                    │
╞════════════════════════╡
│ 139                    │
│ 3329                   │
│ 3731                   │
│ 3761                   │
│ 3849                   │
│ …                      │
│ 9643                   │
│ 9643                   │
│ 9643                   │
│ 9643                   │
│ 9643                   │
└────────────────────────┘

In [6]:

display(df_pandas[df_pandas["MÊS COMPETÊNCIA"]==202401])
print('*********************************')
display(df_polars.filter(pl.col("MÊS COMPETÊNCIA")==202401))

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
0,202401,202303,AC,139,RIO BRANCO,***.511.972-**,1.629112e+10,JANAINA FERREIRA DA SILVA,"800,00"
1,202401,202303,BA,3329,ANGUERA,***.909.745-**,2.047443e+10,TACIANE MARQUES DA SILVA,"750,00"
2,202401,202303,BA,3731,MONTE SANTO,***.872.338-**,2.019538e+10,MAILSON DOS SANTOS SILVA,"650,00"
3,202401,202303,BA,3761,NOVA VICOSA,***.665.905-**,1.272359e+10,IRENI RICARDO GERALDO,"650,00"
4,202401,202303,BA,3849,SALVADOR,***.932.435-**,2.002458e+10,ELIENE GOMES DOS SANTOS,"850,00"
...,...,...,...,...,...,...,...,...,...
20833374,202401,202401,TO,9643,XAMBIOA,,2.032433e+10,ZEILA MARIA BATISTA,"600,00"
20833375,202401,202401,TO,9643,XAMBIOA,***.273.191-**,2.064488e+10,ZENILDE ALVES DOS SANTOS,"600,00"
20833376,202401,202401,TO,9643,XAMBIOA,,1.905866e+10,ZENOLIA RAMOS DA SILVA CARVALHO,"600,00"
20833377,202401,202401,TO,9643,XAMBIOA,***.822.651-**,2.091926e+10,ZILMA ALVES DE BARROS,"440,00"
20833378,202401,202401,TO,9643,XAMBIOA,,2.050120e+10,ZULEIDE DA SILVA E SILVA,"750,00"

*********************************

shape: (20_833_379, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ str       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202401     ┆ 202303     ┆ AC  ┆ 139        ┆ … ┆ ***.511.97 ┆ 1629111520 ┆ JANAINA   ┆ 800,00    │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 5          ┆ FERREIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3329       ┆ … ┆ ***.909.74 ┆ 2047442988 ┆ TACIANE   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 6          ┆ MARQUES   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3731       ┆ … ┆ ***.872.33 ┆ 2019537629 ┆ MAILSON   ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 8          ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3761       ┆ … ┆ ***.665.90 ┆ 1272358908 ┆ IRENI     ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 2          ┆ RICARDO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GERALDO   ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3849       ┆ … ┆ ***.932.43 ┆ 2002458400 ┆ ELIENE    ┆ 850,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 7          ┆ GOMES DOS ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202401     ┆ 202401     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 2032432832 ┆ ZEILA     ┆ 600,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 4          ┆ MARIA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BATISTA   ┆           │
│ 202401     ┆ 202401     ┆ TO  ┆ 9643       ┆ … ┆ ***.273.19 ┆ 2064488199 ┆ ZENILDE   ┆ 600,00    │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 7          ┆ ALVES DOS ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202401     ┆ 202401     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 1905866197 ┆ ZENOLIA   ┆ 600,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ RAMOS DA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CARVALH…  ┆           │
│ 202401     ┆ 202401     ┆ TO  ┆ 9643       ┆ … ┆ ***.822.65 ┆ 2091926382 ┆ ZILMA     ┆ 440,00    │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 2          ┆ ALVES DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BARROS    ┆           │
│ 202401     ┆ 202401     ┆ TO  ┆ 9643       ┆ … ┆            ┆ 2050119994 ┆ ZULEIDE   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 7          ┆ DA SILVA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ E SILVA   ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [7]:
#Estatísticas Descritivas:

display(df_pandas["UF"].describe())

print('*********************************')

display(df_polars.select(pl.col("UF")).describe())

count     41764973
unique          27
top             SP
freq       5148004
Name: UF, dtype: object

*********************************

shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ UF       │
│ ---        ┆ ---      │
│ str        ┆ str      │
╞════════════╪══════════╡
│ count      ┆ 41764973 │
│ null_count ┆ 0        │
│ mean       ┆ null     │
│ std        ┆ null     │
│ min        ┆ AC       │
│ 25%        ┆ null     │
│ 50%        ┆ null     │
│ 75%        ┆ null     │
│ max        ┆ TO       │
└────────────┴──────────┘

In [13]:
#Ordenação dos Dados:

display(df_pandas.sort_values(by="NOME MUNICÍPIO"))

print('*********************************')

display(df_polars.sort("NOME MUNICÍPIO"))

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
5989903,202401,202401,GO,1050,ABADIA DE GOIAS,,1.647251e+10,CAMYLLE VICTORIA BORGES OLIVEIRA,"750,00"
5989995,202401,202401,GO,1050,ABADIA DE GOIAS,***.692.893-**,1.557802e+10,DAISE BARBOSA BARROS,"1110,00"
5989994,202401,202401,GO,1050,ABADIA DE GOIAS,***.912.523-**,2.045520e+10,DAINA DA SILVA SANTOS,"325,00"
5989993,202401,202401,GO,1050,ABADIA DE GOIAS,***.367.971-**,2.013438e+10,DAIARA ARAUJO SANTOS,"800,00"
5989992,202401,202401,GO,1050,ABADIA DE GOIAS,***.074.821-**,2.377689e+10,DAIANY MARIA FERREIRA DA SILVA,"690,00"
...,...,...,...,...,...,...,...,...,...
17743968,202401,202401,SC,950,ZORTEA,,1.430673e+10,LARISSA BARBOSA DOS SANTOS,"750,00"
17743967,202401,202401,SC,950,ZORTEA,,2.136794e+10,KLEYDER ALEJANDRO PRATO MUNOZ,"750,00"
17743966,202401,202401,SC,950,ZORTEA,***.677.629-**,1.607367e+10,KELLE MACIEL,"900,00"
17743972,202401,202401,SC,950,ZORTEA,,2.137482e+10,LUIS FELIPE LIZARDI,"600,00"
38669589,202402,202402,SC,950,ZORTEA,***.677.629-**,1.607367e+10,KELLE MACIEL,"900,00"

*********************************

shape: (41_764_972, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ str       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202401     ┆ 202401     ┆ GO  ┆ 1050       ┆ … ┆ ***.720.55 ┆ 2067087457 ┆ ABIGAIL   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆ 3-**       ┆ 9          ┆ CARDOSO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DO CARMO  ┆           │
│ 202401     ┆ 202401     ┆ GO  ┆ 1050       ┆ … ┆            ┆ 1313221831 ┆ ABRAANA   ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 5          ┆ OLIVEIRA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202401     ┆ GO  ┆ 1050       ┆ … ┆ ***.110.48 ┆ 1613110509 ┆ ADELAIDIA ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 0          ┆ NA        ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ EUGENIO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202401     ┆ GO  ┆ 1050       ┆ … ┆ ***.171.87 ┆ 2045428286 ┆ ADELANE   ┆ 800,00    │
│            ┆            ┆     ┆            ┆   ┆ 2-**       ┆ 3          ┆ COSTA     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BEZERRA   ┆           │
│ 202401     ┆ 202401     ┆ GO  ┆ 1050       ┆ … ┆ ***.690.42 ┆ 2079696824 ┆ ADENILZA  ┆ 690,00    │
│            ┆            ┆     ┆            ┆   ┆ 1-**       ┆ 6          ┆ PEREIRA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ …          ┆ …          ┆ …   ┆ …          ┆ … ┆ …          ┆ …          ┆ …         ┆ …         │
│ 202402     ┆ 202402     ┆ SC  ┆ 950        ┆ … ┆            ┆ 2135941966 ┆ YEIZIS    ┆ 325,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 9          ┆ DANIELA   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GARCIA    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ INFANTE   ┆           │
│ 202402     ┆ 202402     ┆ SC  ┆ 950        ┆ … ┆            ┆ 2135610888 ┆ YELITZA   ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 3          ┆ DEL       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CARMEN    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MOREY     ┆           │
│ 202402     ┆ 202402     ┆ SC  ┆ 950        ┆ … ┆            ┆ 1258748192 ┆ YUGERKIS  ┆ 722,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 0          ┆ CAROLINA  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MARCANO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ CACH…     ┆           │
│ 202402     ┆ 202402     ┆ SC  ┆ 950        ┆ … ┆            ┆ 2139315924 ┆ YUSCARLIS ┆ 580,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 0          ┆ ROCIO     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ ABREU     ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ APONTE    ┆           │
│ 202402     ┆ 202402     ┆ SC  ┆ 950        ┆ … ┆            ┆ 2134528073 ┆ ZULIBETH  ┆ 475,00    │
│            ┆            ┆     ┆            ┆   ┆            ┆ 6          ┆ NAZARETH  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ MAESTRE   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ BOLE…     ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [9]:
#Agregação e Agrupamento:

#exemplo: agrupando por colunas e e contando em cima do que foi selecionado

display(df_pandas.groupby('UF')['NOME MUNICÍPIO'].value_counts())

print('*********************************')

UF  NOME MUNICÍPIO
AC  RIO BRANCO                 87699
    CRUZEIRO DO SUL            28024
    SENA MADUREIRA             18330
    TARAUACA                   17521
    FEIJO                      11452
                               ...
TO  TUPIRAMA                     393
    CRIXAS DO TOCANTINS          351
    SANTA RITA DO TOCANTINS      350
    OLIVEIRA DE FATIMA           324
    SUCUPIRA                     274
Name: count, Length: 5570, dtype: int64

*********************************

In [10]:
#Remoção de Linhas:

#pandas
df_pandas=df_pandas.drop(1)
display(df_pandas.head())

#polars
df_polars=df_polars.slice(1)
display(df_polars.head())

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
0,202401,202303,AC,139,RIO BRANCO,***.511.972-**,1.629112e+10,JANAINA FERREIRA DA SILVA,"800,00"
2,202401,202303,BA,3731,MONTE SANTO,***.872.338-**,2.019538e+10,MAILSON DOS SANTOS SILVA,"650,00"
3,202401,202303,BA,3761,NOVA VICOSA,***.665.905-**,1.272359e+10,IRENI RICARDO GERALDO,"650,00"
4,202401,202303,BA,3849,SALVADOR,***.932.435-**,2.002458e+10,ELIENE GOMES DOS SANTOS,"850,00"
5,202401,202303,BA,3849,SALVADOR,***.081.685-**,1.290199e+10,RITA DE CASSIA SILVA DE SOUZA,"750,00"

shape: (5, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ str       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202401     ┆ 202303     ┆ BA  ┆ 3329       ┆ … ┆ ***.909.74 ┆ 2047442988 ┆ TACIANE   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 6          ┆ MARQUES   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3731       ┆ … ┆ ***.872.33 ┆ 2019537629 ┆ MAILSON   ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 8          ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3761       ┆ … ┆ ***.665.90 ┆ 1272358908 ┆ IRENI     ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 2          ┆ RICARDO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GERALDO   ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3849       ┆ … ┆ ***.932.43 ┆ 2002458400 ┆ ELIENE    ┆ 850,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 7          ┆ GOMES DOS ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3849       ┆ … ┆ ***.081.68 ┆ 1290198505 ┆ RITA DE   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 1          ┆ CASSIA    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SOUZA     ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘

In [11]:
#Adição de Colunas:

#pandas
df_pandas["DK"]=0
display(df_pandas.head())

#polars
df_polars=df_polars.with_columns(pl.lit(0).alias('DK'))
display(df_polars.head())

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA,DK
0,202401,202303,AC,139,RIO BRANCO,***.511.972-**,1.629112e+10,JANAINA FERREIRA DA SILVA,"800,00",0
2,202401,202303,BA,3731,MONTE SANTO,***.872.338-**,2.019538e+10,MAILSON DOS SANTOS SILVA,"650,00",0
3,202401,202303,BA,3761,NOVA VICOSA,***.665.905-**,1.272359e+10,IRENI RICARDO GERALDO,"650,00",0
4,202401,202303,BA,3849,SALVADOR,***.932.435-**,2.002458e+10,ELIENE GOMES DOS SANTOS,"850,00",0
5,202401,202303,BA,3849,SALVADOR,***.081.685-**,1.290199e+10,RITA DE CASSIA SILVA DE SOUZA,"750,00",0

shape: (5, 10)
┌──────────────┬──────────────┬─────┬──────────────┬───┬─────────────┬─────────────┬─────────┬─────┐
│ MÊS          ┆ MÊS          ┆ UF  ┆ CÓDIGO       ┆ … ┆ NIS         ┆ NOME        ┆ VALOR   ┆ DK  │
│ COMPETÊNCIA  ┆ REFERÊNCIA   ┆ --- ┆ MUNICÍPIO    ┆   ┆ FAVORECIDO  ┆ FAVORECIDO  ┆ PARCELA ┆ --- │
│ ---          ┆ ---          ┆ str ┆ SIAFI        ┆   ┆ ---         ┆ ---         ┆ ---     ┆ i32 │
│ i64          ┆ i64          ┆     ┆ ---          ┆   ┆ i64         ┆ str         ┆ str     ┆     │
│              ┆              ┆     ┆ i64          ┆   ┆             ┆             ┆         ┆     │
╞══════════════╪══════════════╪═════╪══════════════╪═══╪═════════════╪═════════════╪═════════╪═════╡
│ 202401       ┆ 202303       ┆ BA  ┆ 3329         ┆ … ┆ 20474429886 ┆ TACIANE     ┆ 750,00  ┆ 0   │
│              ┆              ┆     ┆              ┆   ┆             ┆ MARQUES DA  ┆         ┆     │
│              ┆              ┆     ┆              ┆   ┆             ┆ SILVA       ┆         ┆     │
│ 202401       ┆ 202303       ┆ BA  ┆ 3731         ┆ … ┆ 20195376298 ┆ MAILSON DOS ┆ 650,00  ┆ 0   │
│              ┆              ┆     ┆              ┆   ┆             ┆ SANTOS      ┆         ┆     │
│              ┆              ┆     ┆              ┆   ┆             ┆ SILVA       ┆         ┆     │
│ 202401       ┆ 202303       ┆ BA  ┆ 3761         ┆ … ┆ 12723589082 ┆ IRENI       ┆ 650,00  ┆ 0   │
│              ┆              ┆     ┆              ┆   ┆             ┆ RICARDO     ┆         ┆     │
│              ┆              ┆     ┆              ┆   ┆             ┆ GERALDO     ┆         ┆     │
│ 202401       ┆ 202303       ┆ BA  ┆ 3849         ┆ … ┆ 20024584007 ┆ ELIENE      ┆ 850,00  ┆ 0   │
│              ┆              ┆     ┆              ┆   ┆             ┆ GOMES DOS   ┆         ┆     │
│              ┆              ┆     ┆              ┆   ┆             ┆ SANTOS      ┆         ┆     │
│ 202401       ┆ 202303       ┆ BA  ┆ 3849         ┆ … ┆ 12901985051 ┆ RITA DE     ┆ 750,00  ┆ 0   │
│              ┆              ┆     ┆              ┆   ┆             ┆ CASSIA      ┆         ┆     │
│              ┆              ┆     ┆              ┆   ┆             ┆ SILVA DE    ┆         ┆     │
│              ┆              ┆     ┆              ┆   ┆             ┆ SOUZA       ┆         ┆     │
└──────────────┴──────────────┴─────┴──────────────┴───┴─────────────┴─────────────┴─────────┴─────┘

In [12]:
#Remoção de Colunas:

#pandas
df_pandas=df_pandas.drop(columns=['DK'])
display(df_pandas.head())

#polars
df_polars=df_polars.drop(['DK'])
display(df_polars.head())

,MÊS COMPETÊNCIA,MÊS REFERÊNCIA,UF,CÓDIGO MUNICÍPIO SIAFI,NOME MUNICÍPIO,CPF FAVORECIDO,NIS FAVORECIDO,NOME FAVORECIDO,VALOR PARCELA
0,202401,202303,AC,139,RIO BRANCO,***.511.972-**,1.629112e+10,JANAINA FERREIRA DA SILVA,"800,00"
2,202401,202303,BA,3731,MONTE SANTO,***.872.338-**,2.019538e+10,MAILSON DOS SANTOS SILVA,"650,00"
3,202401,202303,BA,3761,NOVA VICOSA,***.665.905-**,1.272359e+10,IRENI RICARDO GERALDO,"650,00"
4,202401,202303,BA,3849,SALVADOR,***.932.435-**,2.002458e+10,ELIENE GOMES DOS SANTOS,"850,00"
5,202401,202303,BA,3849,SALVADOR,***.081.685-**,1.290199e+10,RITA DE CASSIA SILVA DE SOUZA,"750,00"

shape: (5, 9)
┌────────────┬────────────┬─────┬────────────┬───┬────────────┬────────────┬───────────┬───────────┐
│ MÊS COMPET ┆ MÊS        ┆ UF  ┆ CÓDIGO     ┆ … ┆ CPF        ┆ NIS        ┆ NOME FAVO ┆ VALOR     │
│ ÊNCIA      ┆ REFERÊNCIA ┆ --- ┆ MUNICÍPIO  ┆   ┆ FAVORECIDO ┆ FAVORECIDO ┆ RECIDO    ┆ PARCELA   │
│ ---        ┆ ---        ┆ str ┆ SIAFI      ┆   ┆ ---        ┆ ---        ┆ ---       ┆ ---       │
│ i64        ┆ i64        ┆     ┆ ---        ┆   ┆ str        ┆ i64        ┆ str       ┆ str       │
│            ┆            ┆     ┆ i64        ┆   ┆            ┆            ┆           ┆           │
╞════════════╪════════════╪═════╪════════════╪═══╪════════════╪════════════╪═══════════╪═══════════╡
│ 202401     ┆ 202303     ┆ BA  ┆ 3329       ┆ … ┆ ***.909.74 ┆ 2047442988 ┆ TACIANE   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 6          ┆ MARQUES   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ DA SILVA  ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3731       ┆ … ┆ ***.872.33 ┆ 2019537629 ┆ MAILSON   ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 8-**       ┆ 8          ┆ DOS       ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA     ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3761       ┆ … ┆ ***.665.90 ┆ 1272358908 ┆ IRENI     ┆ 650,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 2          ┆ RICARDO   ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ GERALDO   ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3849       ┆ … ┆ ***.932.43 ┆ 2002458400 ┆ ELIENE    ┆ 850,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 7          ┆ GOMES DOS ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SANTOS    ┆           │
│ 202401     ┆ 202303     ┆ BA  ┆ 3849       ┆ … ┆ ***.081.68 ┆ 1290198505 ┆ RITA DE   ┆ 750,00    │
│            ┆            ┆     ┆            ┆   ┆ 5-**       ┆ 1          ┆ CASSIA    ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SILVA DE  ┆           │
│            ┆            ┆     ┆            ┆   ┆            ┆            ┆ SOUZA     ┆           │
└────────────┴────────────┴─────┴────────────┴───┴────────────┴────────────┴───────────┴───────────┘